name: Build and Deploy

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  FRONTEND_WORKING_DIRECTORY: src/Blauw.Frontend
  FRONTEND_PACKAGE_PATH: src/Blauw.Frontend/dist

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies and build
        working-directory: ${{ env.FRONTEND_WORKING_DIRECTORY }}   
        run: |
          npm install
          npm run build