name: Deploy Accounts

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  ACCOUNTS_APP: blauw-accounts
  ACCOUNTS_APP_PACKAGE_PATH: src/Blauw.Accounts/Blauw.Accounts.FunctionApp/publish
  ACCOUNTS_WORKING_DIRECTORY: src/Blauw.Accounts/Blauw.Accounts.FunctionApp
  DOTNET_CORE_VERSION: 6.0.x
  CONFIGURATION: Release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: Test
        run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal
        
      - name: Publish
        run: dotnet publish "${{ env.ACCOUNTS_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.ACCOUNTS_APP_PACKAGE_PATH }}"
    
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.ACCOUNTS_APP }}
          publish-profile: ${{ secrets.ACCOUNTS_PROD }}
          package: ${{ env.ACCOUNTS_APP_PACKAGE_PATH }}