name: Deploy Frontend

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  FRONTEND_WORKING_DIRECTORY: src/Blauw.Frontend
  FRONTEND_PACKAGE_PATH: src/Blauw.Frontend/dist

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies and build
        working-directory: ${{ env.FRONTEND_WORKING_DIRECTORY }}   
        run: |
          npm install
          npm run build

      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: ${{ env.FRONTEND_PACKAGE_PATH }}
          output_location: ''